name: Build-lede
on:
  workflow_dispatch:
  schedule:
    - cron: 0 12 * * *

jobs:
  
  MT7621:
    runs-on: ubuntu-latest
    steps:
      - name: Prepare environment.
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          bash <(curl -fsSL https://raw.githubusercontent.com/1orz/My-action/master/lede/prenv.sh)

      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          repository: coolsnowwolf/lede

      - name: Download and Load custom configuration
        run: |
          curl -fsSL https://raw.githubusercontent.com/1orz/My-action/master/lede/mt7621/.config >.config
          bash <(curl -fsSL https://raw.githubusercontent.com/1orz/My-action/master/lede/diy.sh)
          make defconfig

      - name: Download package
        run: |
          make download -j8 >/dev/null 2>&1

      - name: When Multi-core compile failure will be rollback to Single core compile
        run: |
          echo -e "Will be use $(nproc) thread compile"
          sudo df -h
          make -j$(nproc) || make -j1 V=sc
          # 这里有个编译报错，必须先clean 一下。 详见 ERROR: package/lean/libcryptopp failed to build.
          make clean
          make -j$(nproc) || make -j1 V=s
          sudo df -h

      - name: Only Upload firmware
        uses: actions/upload-artifact@v2
        if: always()
        with:
          name: mt7621
          path: bin/targets/*/*

      - name: Upload firmware to Download Station
        if: success()
        run: |
          cd bin/targets/*/*
          zip -r -o -q -9 mt7621.zip . -i *.bin
          curl -F "token=${{ secrets.UPLOAD_TOKEN }}" -F "location=Router/lede/XiaoMi/XiaoMi-AC2100" -F "file=@mt7621.zip" ${{ secrets.MAIN_UPLOAD_PROCESSOR }}

  MT7621-Openwrt:
    runs-on: ubuntu-latest
    steps:
      - name: Prepare environment.
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          bash <(curl -fsSL https://raw.githubusercontent.com/1orz/My-action/master/openwrt/prenv.sh)

      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          repository: openwrt/openwrt

      - name: Download and Load custom configuration
        run: |
          curl -fsSL https://raw.githubusercontent.com/1orz/My-action/master/openwrt/mt7621/.config >.config
          bash <(curl -fsSL https://raw.githubusercontent.com/1orz/My-action/master/openwrt/diy.sh)
          make defconfig

      - name: Download package
        run: |
          make download -j8 >/dev/null 2>&1

      - name: When Multi-core compile failure will be rollback to Single core compile
        run: |
          echo -e "Will be use $(nproc) thread compile"
          sudo df -h
          make -j$(nproc) || make -j1 V=sc
          sudo df -h

      - name: Only Upload firmware
        uses: actions/upload-artifact@v2
        if: always()
        with:
          name: mt7621
          path: bin/targets/*/*

      - name: Upload firmware to Download Station
        if: success()
        run: |
          cd bin/targets/*/*
          zip -r -o -q -9 mt7621.zip . -i *.bin
          curl -F "token=${{ secrets.UPLOAD_TOKEN }}" -F "location=Router/openwrt/XiaoMi/XiaoMi-AC2100" -F "file=@mt7621.zip" ${{ secrets.MAIN_UPLOAD_PROCESSOR }}
